// Mocks generated by Mockito 5.4.6 from annotations
// in country_blocker/test/features/country_blocking/data/repositories/country_blocking_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:country_blocker/features/country_blocking/data/datasources/country_blocking_local_data_source.dart'
    as _i2;
import 'package:country_blocker/features/country_blocking/data/models/blocked_country_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CountryBlockingLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryBlockingLocalDataSource extends _i1.Mock
    implements _i2.CountryBlockingLocalDataSource {
  MockCountryBlockingLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.BlockedCountryModel>> getCachedBlockedCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBlockedCountries, []),
            returnValue: _i3.Future<List<_i4.BlockedCountryModel>>.value(
              <_i4.BlockedCountryModel>[],
            ),
          )
          as _i3.Future<List<_i4.BlockedCountryModel>>);

  @override
  _i3.Future<void> cacheBlockedCountries(
    List<_i4.BlockedCountryModel>? countries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBlockedCountries, [countries]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getGlobalBlockingStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalBlockingStatus, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> cacheGlobalBlockingStatus(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#cacheGlobalBlockingStatus, [status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getBlockedCallsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedCallsCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> cacheBlockedCallsCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBlockedCallsCount, [count]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
