// Mocks generated by Mockito 5.4.6 from annotations
// in country_blocker/test/features/country_blocking/domain/usecases/get_blocked_countries_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:country_blocker/core/error/failures.dart' as _i5;
import 'package:country_blocker/features/country_blocking/domain/entities/blocked_country.dart'
    as _i6;
import 'package:country_blocker/features/country_blocking/domain/repositories/country_blocking_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CountryBlockingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCountryBlockingRepository extends _i1.Mock
    implements _i3.CountryBlockingRepository {
  MockCountryBlockingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BlockedCountry>>>
  getBlockedCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedCountries, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.BlockedCountry>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.BlockedCountry>>(
                    this,
                    Invocation.method(#getBlockedCountries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BlockedCountry>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addBlockedCountry(
    _i6.BlockedCountry? country,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addBlockedCountry, [country]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addBlockedCountry, [country]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeBlockedCountry(
    String? phoneCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeBlockedCountry, [phoneCode]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeBlockedCountry, [phoneCode]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> toggleCountryBlocking(
    String? phoneCode,
    bool? isEnabled,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCountryBlocking, [phoneCode, isEnabled]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#toggleCountryBlocking, [
                  phoneCode,
                  isEnabled,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> getGlobalBlockingStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getGlobalBlockingStatus, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#getGlobalBlockingStatus, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> toggleGlobalBlocking() =>
      (super.noSuchMethod(
            Invocation.method(#toggleGlobalBlocking, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#toggleGlobalBlocking, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getBlockedCallsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedCallsCount, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getBlockedCallsCount, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> incrementBlockedCalls() =>
      (super.noSuchMethod(
            Invocation.method(#incrementBlockedCalls, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#incrementBlockedCalls, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
