// Mocks generated by Mockito 5.4.6 from annotations
// in country_blocker/test/features/country_blocking/presentation/notifiers/country_blocking_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:country_blocker/core/error/failures.dart' as _i6;
import 'package:country_blocker/core/usecase/usecase.dart' as _i8;
import 'package:country_blocker/features/country_blocking/domain/entities/blocked_country.dart'
    as _i7;
import 'package:country_blocker/features/country_blocking/domain/repositories/country_blocking_repository.dart'
    as _i2;
import 'package:country_blocker/features/country_blocking/domain/usecases/add_blocked_country.dart'
    as _i9;
import 'package:country_blocker/features/country_blocking/domain/usecases/get_blocked_countries.dart'
    as _i4;
import 'package:country_blocker/features/country_blocking/domain/usecases/increment_blocked_calls.dart'
    as _i13;
import 'package:country_blocker/features/country_blocking/domain/usecases/remove_blocked_country.dart'
    as _i10;
import 'package:country_blocker/features/country_blocking/domain/usecases/toggle_country_blocking.dart'
    as _i11;
import 'package:country_blocker/features/country_blocking/domain/usecases/toggle_global_blocking.dart'
    as _i12;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCountryBlockingRepository_0 extends _i1.SmartFake
    implements _i2.CountryBlockingRepository {
  _FakeCountryBlockingRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetBlockedCountries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBlockedCountries extends _i1.Mock
    implements _i4.GetBlockedCountries {
  MockGetBlockedCountries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryBlockingRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.BlockedCountry>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.BlockedCountry>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.BlockedCountry>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.BlockedCountry>>>);
}

/// A class which mocks [AddBlockedCountry].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddBlockedCountry extends _i1.Mock implements _i9.AddBlockedCountry {
  MockAddBlockedCountry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryBlockingRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i9.AddBlockedCountryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [RemoveBlockedCountry].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveBlockedCountry extends _i1.Mock
    implements _i10.RemoveBlockedCountry {
  MockRemoveBlockedCountry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryBlockingRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i10.RemoveBlockedCountryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [ToggleCountryBlocking].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleCountryBlocking extends _i1.Mock
    implements _i11.ToggleCountryBlocking {
  MockToggleCountryBlocking() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryBlockingRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i11.ToggleCountryBlockingParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [ToggleGlobalBlocking].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleGlobalBlocking extends _i1.Mock
    implements _i12.ToggleGlobalBlocking {
  MockToggleGlobalBlocking() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryBlockingRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [IncrementBlockedCalls].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementBlockedCalls extends _i1.Mock
    implements _i13.IncrementBlockedCalls {
  MockIncrementBlockedCalls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CountryBlockingRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
