// Mocks generated by Mockito 5.4.6 from annotations
// in country_blocker/test/features/country_blocking/presentation/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:country_blocker/core/error/failures.dart' as _i8;
import 'package:country_blocker/core/usecase/usecase.dart' as _i10;
import 'package:country_blocker/features/country_blocking/domain/entities/blocked_country.dart'
    as _i9;
import 'package:country_blocker/features/country_blocking/domain/repositories/country_blocking_repository.dart'
    as _i3;
import 'package:country_blocker/features/country_blocking/domain/usecases/add_blocked_country.dart'
    as _i11;
import 'package:country_blocker/features/country_blocking/domain/usecases/get_blocked_countries.dart'
    as _i7;
import 'package:country_blocker/features/country_blocking/domain/usecases/increment_blocked_calls.dart'
    as _i15;
import 'package:country_blocker/features/country_blocking/domain/usecases/remove_blocked_country.dart'
    as _i12;
import 'package:country_blocker/features/country_blocking/domain/usecases/toggle_country_blocking.dart'
    as _i13;
import 'package:country_blocker/features/country_blocking/domain/usecases/toggle_global_blocking.dart'
    as _i14;
import 'package:country_blocker/shared/services/permissions_service.dart'
    as _i5;
import 'package:dartz/dartz.dart' as _i4;
import 'package:flutter/services.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMethodChannel_0 extends _i1.SmartFake implements _i2.MethodChannel {
  _FakeMethodChannel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountryBlockingRepository_1 extends _i1.SmartFake
    implements _i3.CountryBlockingRepository {
  _FakeCountryBlockingRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PermissionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionsService extends _i1.Mock
    implements _i5.PermissionsService {
  MockPermissionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MethodChannel get platform =>
      (super.noSuchMethod(
            Invocation.getter(#platform),
            returnValue: _FakeMethodChannel_0(
              this,
              Invocation.getter(#platform),
            ),
          )
          as _i2.MethodChannel);

  @override
  _i6.Future<void> requestRole() =>
      (super.noSuchMethod(
            Invocation.method(#requestRole, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> requestPhonePermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPhonePermissions, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasPhonePermissions() =>
      (super.noSuchMethod(
            Invocation.method(#hasPhonePermissions, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [GetBlockedCountries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBlockedCountries extends _i1.Mock
    implements _i7.GetBlockedCountries {
  MockGetBlockedCountries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CountryBlockingRepository);

  @override
  _i6.Future<_i4.Either<_i8.Failure, List<_i9.BlockedCountry>>> call(
    _i10.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<
                  _i4.Either<_i8.Failure, List<_i9.BlockedCountry>>
                >.value(
                  _FakeEither_2<_i8.Failure, List<_i9.BlockedCountry>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i8.Failure, List<_i9.BlockedCountry>>>);
}

/// A class which mocks [AddBlockedCountry].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddBlockedCountry extends _i1.Mock implements _i11.AddBlockedCountry {
  MockAddBlockedCountry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CountryBlockingRepository);

  @override
  _i6.Future<_i4.Either<_i8.Failure, void>> call(
    _i11.AddBlockedCountryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i4.Either<_i8.Failure, void>>.value(
              _FakeEither_2<_i8.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i8.Failure, void>>);
}

/// A class which mocks [RemoveBlockedCountry].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveBlockedCountry extends _i1.Mock
    implements _i12.RemoveBlockedCountry {
  MockRemoveBlockedCountry() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CountryBlockingRepository);

  @override
  _i6.Future<_i4.Either<_i8.Failure, void>> call(
    _i12.RemoveBlockedCountryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i4.Either<_i8.Failure, void>>.value(
              _FakeEither_2<_i8.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i8.Failure, void>>);
}

/// A class which mocks [ToggleCountryBlocking].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleCountryBlocking extends _i1.Mock
    implements _i13.ToggleCountryBlocking {
  MockToggleCountryBlocking() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CountryBlockingRepository);

  @override
  _i6.Future<_i4.Either<_i8.Failure, void>> call(
    _i13.ToggleCountryBlockingParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i4.Either<_i8.Failure, void>>.value(
              _FakeEither_2<_i8.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i8.Failure, void>>);
}

/// A class which mocks [ToggleGlobalBlocking].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleGlobalBlocking extends _i1.Mock
    implements _i14.ToggleGlobalBlocking {
  MockToggleGlobalBlocking() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CountryBlockingRepository);

  @override
  _i6.Future<_i4.Either<_i8.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i4.Either<_i8.Failure, void>>.value(
              _FakeEither_2<_i8.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i8.Failure, void>>);
}

/// A class which mocks [IncrementBlockedCalls].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncrementBlockedCalls extends _i1.Mock
    implements _i15.IncrementBlockedCalls {
  MockIncrementBlockedCalls() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CountryBlockingRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCountryBlockingRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.CountryBlockingRepository);

  @override
  _i6.Future<_i4.Either<_i8.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i4.Either<_i8.Failure, void>>.value(
              _FakeEither_2<_i8.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i8.Failure, void>>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i16.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i6.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
